version: "3.9"

services:
  backend:
    image: ghcr.io/lokiwager/focusbuddy:main
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      DB_HOST: mongodb
      APP_HOST: 0.0.0.0
      ENV: E2E

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: focusbuddy
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
