name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install
        run: |
          pnpm install
      - name: Lint
        run: |
          pnpm lint:eslint
          pnpm lint:prettier
          pnpm lint:type
